### ISSUE TITLE
Release some of the internals as separate libraries?

### ISSUE THREAD

**Issue by tiberiu-popa-qubiz** [proophsoftware/event-machine#112]
Hi

Thanks for this framework, looking forward to use it into my own projects.

In the meantime, I was looking to implement something similar to the messagebox/json validation you did here. I was wondering if you have considered making the json schema validation and/or message box code as separate libraries.  I can really use something like that for the presentation layer in a custom made CQRS project. Maybe others can find it useful to have such an interface, without going graphQL or something.

**Comment by sandrokeil** [comment]
We will think about that for [version 2](https://proophsoftware.github.io/event-machine/news/2018-09-08-future.html). The current focus is version 1.

**Comment by codeliner** [comment]
Current implementation of Event Machine (which will become v1.0 soon) is based on prooph components and some other libraries. It "just" combines them to a framework.

For example, Message validation based on JSON Schema is done with a [custom prooph Message Factory](https://github.com/proophsoftware/event-machine/blob/master/src/Messaging/GenericJsonSchemaMessageFactory.php)
and a JSON Schema validator using [justinrainbow/json-schema](https://github.com/justinrainbow/json-schema) by default.
The message box is heavily inspired by [prooph/http-middleware](https://github.com/prooph/http-middleware) but is a custom implementation because messages are forwarded to Event Machine instead of prooph/service-bus. 

You could use the same building blocks outside of Event Machine.
I think all [JSON Schema helpers](https://github.com/proophsoftware/event-machine/tree/master/src/JsonSchema) will become a separate lib in Event Machine v2.0. Not sure about the message box because it's only a few lines of code and uses Event Machine to dispatch messages.

**Comment by codeliner** [comment]
Event Engine will be split into smaller packages. Information can be found here: https://github.com/event-engine/php-engine/releases

Closing the issue.
