### ISSUE TITLE
JSON schema validation optimization

### ISSUE THREAD

**Issue by camuthig** [proophsoftware/event-machine#82]
In the `JustinRainbowJsonSchemaAssertion::assert` implementation, we are currently forced to do something like the below to ensure empty objects and empty arrays are differentiated.

```php
$enforcedObjectData = json_decode(json_encode($data));
$jsonSchema = json_decode(json_encode($jsonSchema));
```

With a large enough schema, this decode/encode pattern could become problematic. This isn't really a big issue right now, I think, but I wanted to get it documented.

**Comment by codeliner** [comment]
good point. In a production application we use that technique with a very large schema and performance is still ok because PHP7 is really fast on arrays.

Anyway, as far as I remember an option was added to the json schema lib to work with assoc instead of stdClass objects. We can try this option. Did not find the time yet to try it.

**Comment by codeliner** [comment]
Event Engine ships with an alternative JSON Schema validation lib, which is much faster (~30%): https://github.com/event-engine/php-engine/blob/master/json-schema/src/OpisJsonSchema.php
